global:
  scrape_interval: 15s  # Частота опроса метрик

scrape_configs:
  - job_name: 'endpoint-with-nosql'
    static_configs:
      - targets: ['host.docker.internal:3090']
    metrics_path: '/actuator/prometheus'

  - job_name: 'endpoint-with-sql'
    static_configs:
      - targets: ['host.docker.internal:3080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'endpoint-without-sql'
    static_configs:
      - targets: ['host.docker.internal:3050']
    metrics_path: '/actuator/prometheus'

  # Опрос PostgreSQL для микросервиса с NoSQL
  - job_name: 'endpoint-with-nosql-db'
    static_configs:
      - targets: ['host.docker.internal:9188']
    metrics_path: '/metrics'

  # Опрос PostgreSQL для микросервиса с SQL
  - job_name: 'endpoint-with-sql-db-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']
    metrics_path: '/metrics'

  # Опрос Redis
  - job_name: 'redis-server-exporter'
    static_configs:
      - targets: ['host.docker.internal:9121']  # Порт Redis
    metrics_path: '/metrics'
