spring:
  application:
    name: Checker_microservice
  datasource:
    url: jdbc:postgresql://checker-microservice-db:5432/checker_db
#    url: jdbc:postgresql://localhost:5432/checker_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

url:
  get_token:
    key: "api/v1/get-token"
  check_status:
    key: "api/v1/check-status"

server:
  port: 8082