spring:
  application:
    name: Checker_microservice
  datasource:
#    url: jdbc:postgresql://checker_db:5432/checker_db
    url: jdbc:postgresql://localhost:5432/checker_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: smtp.mail.ru
    port: 465
    username: nik.malykh.2024@mail.ru
    password: PLmpfSCAvDhCzrtzYSiw
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

    default-encoding: UTF-8

  cache:
    type: redis
  data:
    redis:
      host: redis-server
      port: 6379

url:
  tg:
    key: "http://localhost:9001"
  tg_req:
    key: "/notify"
  get_token:
    key: "api/v1/get-token"
  check_status:
    key: "api/v1/check-status"

email:
  from: "nik.malykh.2024@mail.ru"

server:
  port: 8082